apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
{{- if .Values.solr.enabled }}
  INDEX_HOST: {{ .Values.solr.host | quote  }}
  INDEX_PORT: {{ .Values.solr.port | quote  }}
{{- end }}
{{- if .Values.mysql.enabled }}
  DB_USER: {{ .Values.mysql.mysqlUser | quote }}
  DB_HOST: "{{ .Release.Name }}-mysql"
  DB_DATABASE: {{ .Values.mysql.mysqlDatabase | quote }}
{{- else if .Values.postgresql.enabled }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername | quote }}
  DB_HOST: "{{ .Release.Name }}-postgresql"
  DB_DATABASE: {{ .Values.postgresql.postgresqlDatabase | quote }}
{{- else }}
  {{- if .Values.externalDB.user.value }}
  DB_USER: {{ .Values.externalDB.user.value | quote }}
  {{- end }}
  {{- if .Values.externalDB.host.value }}
  DB_HOST: {{ .Values.externalDB.host.value | quote }}
  {{- end }}
  {{- if .Values.externalDB.database.value }}
  DB_DATABASE: {{ .Values.externalDB.database.value | quote }}
  {{- end }}
{{- end }}
{{- with .Values.tomcat }}
{{- if .customServerConfig }}
  server.xml: |-
    {{- $.Files.Get "files/server.xml" | nindent 4 }}
{{- end }}
{{- end }}
# {{- range $key, $value := .Values.database }}
#   {{ $key }}: {{ $value | indent 4 }}
# {{- end }}