{{- if .Values.ingress.enabled -}}
{{- $defaultServiceHost := include "default-service-host" . | trim -}}
{{- $defaultGlowrootHost := printf "glowroot-%s" $defaultServiceHost -}}
{{- $allHosts := $defaultServiceHost | append (default (list) .Values.ingress.hosts) | compact -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
  labels:
    app: "{{ template "fullname" . }}"
    version: "{{ .Chart.AppVersion }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  tls:
    {{- if .Values.ingress.tls }}
      {{- toYaml .Values.ingress.tls | nindent 4 }}
    {{- end }}
    {{- include "default-service-host-tls" . | nindent 4 }}
  rules:
  {{- if $allHosts }}
    {{- range $host := $allHosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "fullname" $ }}
          servicePort: {{ $.Values.service.externalPort }}
    {{- end }}
  {{- end }}
  {{- with .Values.glowroot }}
  {{- if and .enabled .ingress }}
  - host: {{ $defaultGlowrootHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "fullname" $ }}
          servicePort: glowroot
  {{- end }}
  {{- end }}
{{- end -}}



{{- define "default-service-host" }}
{{- $serviceName := include "fullname" . -}}
{{- if .Values.clusterDomain -}}
  {{- if .Values.clusterGatewayEnabled }}
    {{- printf "%s.%s.gw.%s.lenovo.com" $serviceName .Release.Namespace .Values.clusterDomain -}}
  {{- else -}}
    {{- printf "%s.%s.k8s.%s.lenovo.com" $serviceName .Release.Namespace .Values.clusterDomain -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "default-service-host-tls" }}
{{- $defaultServiceHost := include "default-service-host" . | trim -}}
{{- if and .Values.clusterGatewaySecured $defaultServiceHost -}}
{{- $secretName := include "host-to-secret" $defaultServiceHost -}}
- hosts:
  - {{ $defaultServiceHost }}
  secretName: {{ $secretName }}
{{- end -}}
{{- end -}}

{{/*
Translate host to secret name
*/}}
{{- define "host-to-secret" }}
{{- $list := . | splitList "." | rest -}}
{{- $list := prepend $list "star" -}}
{{ join "-" $list }}
{{- end -}}