apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
{{- if .Values.mysql.enabled }}
  DB_PASSWORD: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
{{- else if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- else }}
  {{- if .Values.externalDB.password.value }}
  DB_PASSWORD: {{ .Values.externalDB.password.value | b64enc | quote }}
  {{- end }}
{{- end }}