apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "fullname" . }}"
    version: "{{ .Chart.AppVersion }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  {{- with .Values.glowroot }}
  {{- if .enabled }}
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: glowroot
  {{- end }}
  {{- end }}
  sessionAffinity: ClientIP
  selector:
    app: {{ template "fullname" . }}